package view;


import dao.ClienteDAO;
import dao.LivroDAO;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.Cliente;
import model.Livro;
import table.ClienteTableModel;
import table.LivroTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class Tela extends javax.swing.JFrame {
    
    Livro livro = new Livro();
    LivroDAO livroD = new LivroDAO();
    
    Cliente cliente = new Cliente();
    ClienteDAO clienteD = new ClienteDAO();


    /** Creates new form Tela */
    public Tela() throws ParseException {
        initComponents();
        setLocationRelativeTo(null);
        tbCliente.setModel(new ClienteTableModel (new ClienteDAO().listarTodos()));
        tbLivro.setModel(new LivroTableModel (new LivroDAO().listarTodos()));  
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfLivroPags = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfLivroNome = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfLivroAno = new javax.swing.JTextField();
        tfLivroEditora = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfLivroAutor = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLivro = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        tfClienteCidade = new javax.swing.JTextField();
        tfClienteNome = new javax.swing.JTextField();
        tfClienteNumero = new javax.swing.JTextField();
        tfClienteRua = new javax.swing.JTextField();
        tfClienteEmail = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        tfClienteCpf = new javax.swing.JFormattedTextField();
        tfClienteTelefone = new javax.swing.JFormattedTextField();
        tfClienteUf = new javax.swing.JFormattedTextField();
        tfClienteCep = new javax.swing.JFormattedTextField();
        panel1 = new java.awt.Panel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLivro1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        btSalvar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dashboard");
        setFont(new java.awt.Font("Sitka Subheading", 0, 10)); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel1.setText("Cliente:");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel4.setText("Número");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel5.setText("CEP");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel6.setText("UF");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel7.setText("Cidade");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel8.setText("Rua");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel10.setText("Telefone");

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel11.setText("Ano");

        tfLivroPags.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroPags.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroPags.setForeground(new java.awt.Color(36, 36, 36));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel12.setText("Genero");

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel13.setText("N. de Páginas");

        jLabel14.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel14.setText("Autor");

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        jLabel17.setText("LIVRO");

        tfLivroNome.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroNome.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroNome.setForeground(new java.awt.Color(36, 36, 36));

        jLabel18.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel18.setText("Nome");

        tfLivroAno.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroAno.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroAno.setForeground(new java.awt.Color(36, 36, 36));
        tfLivroAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLivroAnoActionPerformed(evt);
            }
        });

        tfLivroEditora.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroEditora.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroEditora.setForeground(new java.awt.Color(36, 36, 36));
        tfLivroEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLivroEditoraActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jLabel20.setText("Editora");

        tfLivroAutor.setBackground(new java.awt.Color(210, 190, 179));
        tfLivroAutor.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfLivroAutor.setForeground(new java.awt.Color(36, 36, 36));

        btSalvar.setBackground(new java.awt.Color(145, 119, 102));
        btSalvar.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Inserir");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(145, 119, 102));
        btExcluir.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Excluir");

        btLimpar.setBackground(new java.awt.Color(145, 119, 102));
        btLimpar.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btLimpar.setText("Limpar");
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimparMouseClicked(evt);
            }
        });
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(210, 190, 179));
        jComboBox1.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "CLIENTE", "LIVRO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        tbLivro.setBackground(new java.awt.Color(210, 190, 179));
        tbLivro.setFont(new java.awt.Font("Noto Serif CJK KR", 0, 15)); // NOI18N
        tbLivro.setForeground(new java.awt.Color(36, 36, 36));
        tbLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Ano", "Editora", "Autor", "Num de paginas", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbLivro.setEnabled(false);
        tbLivro.setGridColor(new java.awt.Color(161, 95, 64));
        jScrollPane1.setViewportView(tbLivro);

        jLabel15.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        jLabel15.setText("CLIENTE");

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        jLabel19.setText("Ficha do Livro:");

        tbCliente.setBackground(new java.awt.Color(210, 190, 179));
        tbCliente.setFont(new java.awt.Font("Noto Serif CJK KR", 0, 15)); // NOI18N
        tbCliente.setForeground(new java.awt.Color(36, 36, 36));
        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "CPF", "Nome", "CEP", "Numero", "Rua", "Cidade", "UF", "Email", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbCliente.setEnabled(false);
        tbCliente.setFocusCycleRoot(true);
        tbCliente.setGridColor(new java.awt.Color(161, 95, 64));
        tbCliente.setInheritsPopupMenu(true);
        jScrollPane2.setViewportView(tbCliente);

        tfClienteCidade.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteCidade.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteCidade.setForeground(new java.awt.Color(36, 36, 36));
        tfClienteCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteCidadeActionPerformed(evt);
            }
        });

        tfClienteNome.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteNome.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteNome.setForeground(new java.awt.Color(36, 36, 36));
        tfClienteNome.setCaretColor(new java.awt.Color(161, 111, 111));
        tfClienteNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tfClienteNumero.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteNumero.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteNumero.setForeground(new java.awt.Color(36, 36, 36));

        tfClienteRua.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteRua.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteRua.setForeground(new java.awt.Color(36, 36, 36));

        tfClienteEmail.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteEmail.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteEmailActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(210, 190, 179));
        jComboBox2.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(36, 36, 36));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher", "Romance", "Terror", "Ficcao" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        tfClienteCpf.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteCpf.setForeground(new java.awt.Color(36, 36, 36));
        try {
            tfClienteCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfClienteCpf.setText("");
        tfClienteCpf.setCaretColor(new java.awt.Color(161, 95, 64));
        tfClienteCpf.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteCpf.setSelectionColor(new java.awt.Color(161, 95, 64));
        tfClienteCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteCpfActionPerformed(evt);
            }
        });

        tfClienteTelefone.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteTelefone.setForeground(new java.awt.Color(36, 36, 36));
        try {
            tfClienteTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfClienteTelefone.setText("");
        tfClienteTelefone.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteTelefoneActionPerformed(evt);
            }
        });

        tfClienteUf.setBackground(new java.awt.Color(210, 190, 179));
        try {
            tfClienteUf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfClienteUf.setText("");
        tfClienteUf.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tfClienteUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteUfActionPerformed(evt);
            }
        });

        tfClienteCep.setBackground(new java.awt.Color(210, 190, 179));
        tfClienteCep.setForeground(new java.awt.Color(36, 36, 36));
        try {
            tfClienteCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfClienteCep.setText("");
        tfClienteCep.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/50+ Free Dark Academia Wallpaper For iPhone Options _.jpeg"))); // NOI18N
        jLabel16.setText("jLabel16");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        tbLivro1.setBackground(new java.awt.Color(210, 190, 179));
        tbLivro1.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        tbLivro1.setForeground(new java.awt.Color(36, 36, 36));
        tbLivro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Mês", "Cliente", "Livro Sorteado", "Autor", "Gênero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbLivro1.setEnabled(false);
        tbLivro1.setGridColor(new java.awt.Color(161, 95, 64));
        jScrollPane3.setViewportView(tbLivro1);

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        jLabel21.setText("RESULTADOS DO SORTEIO:");

        btSalvar1.setBackground(new java.awt.Color(161, 101, 64));
        btSalvar1.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        btSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar1.setText("Realizar Sorteio");
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfClienteCidade)
                                    .addComponent(tfClienteNome)
                                    .addComponent(tfClienteNumero)
                                    .addComponent(tfClienteRua)
                                    .addComponent(tfClienteEmail)
                                    .addComponent(tfClienteCpf)
                                    .addComponent(tfClienteTelefone)
                                    .addComponent(tfClienteUf)
                                    .addComponent(tfClienteCep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel11)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel12))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfLivroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfLivroAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfLivroPags, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(2, 2, 2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfLivroAno, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                            .addComponent(tfLivroEditora)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(265, 265, 265))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel19))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tfClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLivroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tfClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(tfLivroAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(tfLivroEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfClienteCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(tfLivroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfClienteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tfLivroPags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfClienteRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfClienteCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfClienteUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimpar)
                            .addComponent(btExcluir)
                            .addComponent(btSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void tfClienteUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClienteUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClienteUfActionPerformed

    private void tfClienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClienteTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClienteTelefoneActionPerformed

    private void tfLivroEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLivroEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLivroEditoraActionPerformed

    private void tfClienteCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClienteCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClienteCpfActionPerformed

    private void tfClienteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClienteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClienteEmailActionPerformed

    private void tfClienteCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClienteCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClienteCidadeActionPerformed

    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparMouseClicked

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Selecione uma opção válida para o cadastro!", "Erro!", JOptionPane.WARNING_MESSAGE);
        }
        
        else if (jComboBox1.getSelectedIndex() == 1){
            
            cliente.setCpf(tfClienteCpf.getText());
            cliente.setNome(tfClienteNome.getText());
            cliente.setCep(tfClienteCep.getText());
            //cliente.setNumero(tfCliente.getText());
            cliente.setRua(tfClienteCep.getText());
            cliente.setCidade(tfClienteCep.getText());
            cliente.setUf(tfClienteCep.getText());
            cliente.setEmail(tfClienteCep.getText());
            cliente.setTelefone(tfClienteCep.getText());            
            
        }
        
        else{
            
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfLivroAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLivroAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLivroAnoActionPerformed

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Panel panel1;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTable tbLivro;
    private javax.swing.JTable tbLivro1;
    private javax.swing.JFormattedTextField tfClienteCep;
    private javax.swing.JTextField tfClienteCidade;
    private javax.swing.JFormattedTextField tfClienteCpf;
    private javax.swing.JTextField tfClienteEmail;
    private javax.swing.JTextField tfClienteNome;
    private javax.swing.JTextField tfClienteNumero;
    private javax.swing.JTextField tfClienteRua;
    private javax.swing.JFormattedTextField tfClienteTelefone;
    private javax.swing.JFormattedTextField tfClienteUf;
    private javax.swing.JTextField tfLivroAno;
    private javax.swing.JTextField tfLivroAutor;
    private javax.swing.JTextField tfLivroEditora;
    private javax.swing.JTextField tfLivroNome;
    private javax.swing.JTextField tfLivroPags;
    // End of variables declaration//GEN-END:variables

}
